[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mymoneydapp = "EeuYUHgTybmUwweikf2CdGBSFoHNpVNjHVgjUzRPfiLo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Gorkee\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
